### ISSUE TITLE
IOLinc sensor reports backwards

### ISSUE THREAD

**Issue by teharris1** [pyinsteon/pyinsteon#191]
The IO sensor reports open when closed and closed when open.

**Comment by danielduerr** [comment]
@teharris1 I just noticed this ticket, and might be able to help. I have this exact situation on one of my IOLinc sensors (for a magnetic garage door sensor) so I can confirm it is real. But, at least in my case, this is by design due to how I programmed the sensor.

By default, an IOLinc will send an ON when the sensor is closed/shorted, and an OFF when the sensor is opened. But if you change this setting, like I did in my previous controller software, the IOLinc will emit an OFF when sensor is closed/shorted, and an ON when the sensor is opened. So I've been living with the backwards sensor since I started, knowing at least in my case it was not your fault, but instead mine.

Here's the function from my abandoned PHP-based HA system which set the IOLinc operating flags:
```
    /**
     * @param array $args
     * @param bool $reset
     * @return array
     */
    public function cmdsSetIolinc(array $args, $reset = false) {
        list($plock, $sensor_open_on, $relay_mirrors_sensor, $relay_momentary) = $args;
        $commands = [];
        $commands[] = $this->cmdSetOpFlags(($plock ? '00' : '01'), ($this->getDevice()->protocol == parent::protocol_i2cs ? [] : null));
        $commands[] = $this->cmdSetOpFlags(($sensor_open_on ? '0E' : '0F'), ($this->getDevice()->protocol == parent::protocol_i2cs ? [] : null));
        $commands[] = $this->cmdSetOpFlags(($relay_mirrors_sensor ? '04' : '05'), ($this->getDevice()->protocol == parent::protocol_i2cs ? [] : null));
        $commands[] = $this->cmdSetOpFlags(($relay_momentary ? '06' : '07'), ($this->getDevice()->protocol == parent::protocol_i2cs ? [] : null));
        return $commands;
    }
```
The second one there, based on a `bool $sensor_open_on` was driven from a toggle that allowed me to set the device between the default mode and the alternate mode I described above.  So if I wanted the default behavior, I'd transmit a `0x20 0x0f` to the device, and if I wanted the alternate behavior, I'd transmit a `0x20 0x0e` to the device.  Make sense?

In my case, the reason for using the alternate mode is that this same IOLinc is tied to a button on a Keypad in the house via ALDB links, and I want the button to be lit (ON) when the garage door is open, and unlit (OFF) when it is closed.

**Comment by teharris1** [comment]
Yes, you are right. Thanks for filling in a gap for me. The state of that property should be checked before determining open/closed. Do you know if the status command is inverted based on the value of that prosperity?

**Comment by danielduerr** [comment]
@teharris1 awesome, happy to help. Here was my status parser function which shares the same `bool $sensor_open_on` parameter:
```    /**
     * @param string $device_status
     * @param null|int $status_index
     * @return array
     */
    public function parseIolincSensorStatus($device_status, $status_index = null) {
        $label = $this->getLabel('sensor', 'Sensor');
        $sensor_open_on = ($this->hasDevice() ? (bool)$this->getDevice()->getProperty('iolinc', 'sensor_open_on') : false);
        return [
            'status' => ($device_status == '0X01' ? devices_status::status_on : devices_status::status_off),
            'detail' => (($device_status == '0X01' && !$sensor_open_on) || ($device_status != '0X01' && $sensor_open_on) ? $label . ' Closed' : $label . ' Open'),
        ];
    }
```
I believe the status '0X01' is always interpreted as 'ON' regardless of the position of this switch.  The state of the contact (Closed or Open) is then determined by the 'detail' line above.  Make sense?
