### ISSUE TITLE
Connection retry every 0.1 seconds

### ISSUE THREAD

**Issue by michaeldavie** [pyinsteon/pyinsteon#68]
<img width="1391" alt="Screen Shot 2021-01-29 at 1 42 21 PM" src="https://user-images.githubusercontent.com/16008714/106336174-56efc700-625c-11eb-880a-22a7301aa63e.png">

The Insteon hub v2 appears to use a non-standard TCP response, causing a retry to be triggered every 0.1 seconds as pictured above. The issue seems to be related to https://github.com/pyinsteon/pyinsteon/blob/master/pyinsteon/protocol/http_reader_writer.py, as it has a 0.1 second retry period.

**Comment by teharris1** [comment]
You are misunderstanding the code. PRIOR_CONN_CLOSE_PAUSE is used to give a prior connection time to close. The hub can only sustain one connection at a time. If you try to connect a second time the entire hub locks up. It is a terrible design. 

The actual line of code that determines the connection rate is:

https://github.com/pyinsteon/pyinsteon/blob/master/pyinsteon/protocol/http_transport.py#L194

Where READ_WAIT is set to .5 seconds. The Hub can only store 100 bytes of data and a single message can be 25 bytes long so there are many scenarios that the Hub can only store 4 messages. In the case of reading the ALDB or other message types that are a continuous stream of 25 bytes each the .5 second refresh rate ensures that the module does not lose messages. There are many threads about this on other forums. It is possible for me to set this as a tunable item but in any case the range for this should be between 0.3 seconds and 0.7 seconds. If you go all the way up to 1 second you are almost guaranteed to lose messages.

**Comment by michaeldavie** [comment]
I don’t yet understand the cause, but the library is initiating a
connection to the hub and making the same HTTP request every 0.1 seconds,
despite receiving a successful response. I suspect it may be mishandling a
server disconnection error raised by aiohttp when the hub sends the RST
packets shown above.

**Comment by teharris1** [comment]
I am starting a new patch to focus on as many bugs as I can and I really want to address this one since it the main suspect in connection lockouts with the hub. As you may know, the Hub only allows one concurrent connection and when a connection is made (from the Hub perspective) and the client disconnects but the Hub never closes the connection, subsequent calls all fail with no possible means of recovery. 

So why do you suspect the ServerDisconnectedError is being raised? What tool did you use to capture the data above, was that wireshark or something like that?

**Comment by michaeldavie** [comment]
Great! I captured the packets by running `tcpdump` on my router and feeding them to Wireshark to capture the screenshot above. It seems logical that `aiohttp` would raise a `ServerDisconnectedError` when it receives a packet with the `RST` flag set from the server, but I haven't confirmed this.

**Comment by teharris1** [comment]
Do you believe this would address the issue:
https://github.com/aio-libs/aiohttp/issues/3433

**Comment by teharris1** [comment]
Doh. I found the issue and it is my mistake. The problem comes in this line:

https://github.com/pyinsteon/pyinsteon/blob/master/pyinsteon/protocol/http_transport.py#L193

It should be:
`            if not self.is_closing():`

Without the `()` the `await asyncio.sleep(READ_WAIT)` line is never executed so the reader reads as soon as possible which turns out to be about 0.1 seconds.

**Comment by michaeldavie** [comment]
Nice! Once you patch it I can test it out on my setup.

**Comment by michaeldavie** [comment]
I made this change manually and it looks like the read spacing is down to 0.5s as anticipated. Thanks for tracking this down!
